//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YtbDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YtbDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的下载地址是否正确 的本地化字符串。
        /// </summary>
        internal static string CheckDownloadUrl {
            get {
                return ResourceManager.GetString("CheckDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的输出目录是否正确 的本地化字符串。
        /// </summary>
        internal static string CheckOutputDir {
            get {
                return ResourceManager.GetString("CheckOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的代理地址是否正确 的本地化字符串。
        /// </summary>
        internal static string CheckProxyUrl {
            get {
                return ResourceManager.GetString("CheckProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载过程中退出程序可能导致下载的文件损坏，是否继续 的本地化字符串。
        /// </summary>
        internal static string ExitWarning {
            get {
                return ResourceManager.GetString("ExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string ExitWarningCaption {
            get {
                return ResourceManager.GetString("ExitWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infomation 的本地化字符串。
        /// </summary>
        internal static string SaveLogCompletionCaption {
            get {
                return ResourceManager.GetString("SaveLogCompletionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveLogCompletionMessage {
            get {
                return ResourceManager.GetString("SaveLogCompletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文档(*.log)|*.log 的本地化字符串。
        /// </summary>
        internal static string SaveLogDialogFilter {
            get {
                return ResourceManager.GetString("SaveLogDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择保存位置 的本地化字符串。
        /// </summary>
        internal static string SaveLogDialogTitle {
            get {
                return ResourceManager.GetString("SaveLogDialogTitle", resourceCulture);
            }
        }
    }
}
