//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YtbDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YtbDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的下载地址是否正确 的本地化字符串。
        /// </summary>
        public static string CheckDownloadUrlMessage {
            get {
                return ResourceManager.GetString("CheckDownloadUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的输出目录是否正确 的本地化字符串。
        /// </summary>
        public static string CheckOutputDirMessage {
            get {
                return ResourceManager.GetString("CheckOutputDirMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的代理地址是否正确 的本地化字符串。
        /// </summary>
        public static string CheckProxyUrlMessage {
            get {
                return ResourceManager.GetString("CheckProxyUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载字幕需指定对应的语言 的本地化字符串。
        /// </summary>
        public static string CheckSubLangsUrlMessage {
            get {
                return ResourceManager.GetString("CheckSubLangsUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除日志 的本地化字符串。
        /// </summary>
        public static string ClearLogBtnHelpText {
            get {
                return ResourceManager.GetString("ClearLogBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载字幕(YouTube-Dl) 的本地化字符串。
        /// </summary>
        public static string DownloadSubHelpText {
            get {
                return ResourceManager.GetString("DownloadSubHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载地址： 的本地化字符串。
        /// </summary>
        public static string DownloadUrlHelpText {
            get {
                return ResourceManager.GetString("DownloadUrlHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用代理 的本地化字符串。
        /// </summary>
        public static string EnableProxyHelpText {
            get {
                return ResourceManager.GetString("EnableProxyHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具选择： 的本地化字符串。
        /// </summary>
        public static string EngineSelectionHelpText {
            get {
                return ResourceManager.GetString("EngineSelectionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载过程中退出可能导致文件损坏，请等待停止下载后再退出 的本地化字符串。
        /// </summary>
        public static string ExitWarningMessage {
            get {
                return ResourceManager.GetString("ExitWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略错误(YouTube-Dl) 的本地化字符串。
        /// </summary>
        public static string IgnoreErrorHelpText {
            get {
                return ResourceManager.GetString("IgnoreErrorHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅下载音频(YouTube-Dl) 的本地化字符串。
        /// </summary>
        public static string IsAudioOnlyHelpText {
            get {
                return ResourceManager.GetString("IsAudioOnlyHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试模式 的本地化字符串。
        /// </summary>
        public static string IsDebugHelpText {
            get {
                return ResourceManager.GetString("IsDebugHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载列表 的本地化字符串。
        /// </summary>
        public static string IsPlaylistHelpText {
            get {
                return ResourceManager.GetString("IsPlaylistHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入配置文件失败 的本地化字符串。
        /// </summary>
        public static string LoadConfigFailureMessage {
            get {
                return ResourceManager.GetString("LoadConfigFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多选项 的本地化字符串。
        /// </summary>
        public static string MoreOptionHelpText {
            get {
                return ResourceManager.GetString("MoreOptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开输出目录 的本地化字符串。
        /// </summary>
        public static string OpenOutputDirHelpText {
            get {
                return ResourceManager.GetString("OpenOutputDirHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出目录： 的本地化字符串。
        /// </summary>
        public static string OutputDirHelpText {
            get {
                return ResourceManager.GetString("OutputDirHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置文件失败 的本地化字符串。
        /// </summary>
        public static string SaveConfigFailureMessage {
            get {
                return ResourceManager.GetString("SaveConfigFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string SetOutputDirHelpText {
            get {
                return ResourceManager.GetString("SetOutputDirHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string StartBtnHelpText {
            get {
                return ResourceManager.GetString("StartBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string StopBtnHelpText {
            get {
                return ResourceManager.GetString("StopBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YtbDownloader 的本地化字符串。
        /// </summary>
        public static string WinTitle {
            get {
                return ResourceManager.GetString("WinTitle", resourceCulture);
            }
        }
    }
}
